"""ReportLab PDF reporter for the GDPR Art.9 assessment report.

Generates a multi-page PDF with:
  Cover page — system name, overall score, risk rating
  Executive Summary — obligation-level table
  Findings — all GAP and PARTIAL checks with evidence + remediation
  Roadmap — prioritised remediation table
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Union

from biometric_auth.models.results import EvaluationResult, GDPRReport

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    _REPORTLAB_AVAILABLE = True
except ImportError:
    _REPORTLAB_AVAILABLE = False

# Colour palette
_NAVY = colors.HexColor("#003087")
_TEAL = colors.HexColor("#007A73")
_RED = colors.HexColor("#C8102E")
_AMBER = colors.HexColor("#F5A623")
_GREEN = colors.HexColor("#007A33")
_LIGHT_GREY = colors.HexColor("#F4F4F4")
_MID_GREY = colors.HexColor("#CCCCCC")

_STATUS_COLOURS = {
    "SATISFIED": _GREEN,
    "PARTIAL": _AMBER,
    "GAP": _RED,
    "N/A": colors.grey,
}
_RISK_COLOURS = {
    "LOW": _GREEN,
    "MEDIUM": _AMBER,
    "HIGH": _RED,
    "CRITICAL": _RED,
}


def _check_reportlab() -> None:
    if not _REPORTLAB_AVAILABLE:
        raise ImportError(
            "reportlab is required for PDF reports. Install with: pip install reportlab"
        )


def generate_pdf(
    report: GDPRReport,
    evaluation_result: EvaluationResult | None = None,
    output: str | Path | None = None,
) -> bytes:
    """Generate a GDPR Art.9 assessment PDF report.

    Args:
        report: GDPRReport from run_art9_assessment().
        evaluation_result: Optional EvaluationResult for the performance section.
        output: Optional path to write PDF. If None, returns bytes only.

    Returns:
        PDF content as bytes.
    """
    _check_reportlab()

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"GDPR Art.9 Assessment — {report.system_name}",
        author="biometric-auth-analysis",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], textColor=_NAVY, fontSize=18, spaceAfter=6)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=_TEAL, fontSize=13, spaceAfter=4)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=13)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, leading=11, textColor=colors.grey)
    finding_style = ParagraphStyle(
        "Finding", parent=styles["Normal"], fontSize=8, leading=11, leftIndent=6
    )

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────
    story.append(Spacer(1, 20 * mm))
    story.append(Paragraph("GDPR Article 9 Compliance Assessment", h1))
    story.append(Paragraph(f"<b>{report.system_name}</b>", h1))
    story.append(HRFlowable(width="100%", thickness=2, color=_NAVY))
    story.append(Spacer(1, 4 * mm))

    risk_colour = _RISK_COLOURS.get(report.risk_rating, colors.black)
    score_pct = f"{report.overall_score:.1%}"
    cover_data = [
        ["Overall Score", score_pct],
        ["Compliance Status", report.overall_status],
        ["Risk Rating", report.risk_rating],
        ["Satisfied Threshold", f"{report.satisfied_threshold:.0%} (Art.9 — always 90%)"],
        ["Report Date", report.generated_at.strftime("%d %B %Y %H:%M UTC")],
        ["System Description", report.system_description or "—"],
    ]
    cover_table = Table(cover_data, colWidths=[55 * mm, 110 * mm])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), _LIGHT_GREY),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, _MID_GREY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, _LIGHT_GREY]),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "This report was generated by <b>biometric-auth-analysis</b> "
        "(github.com/Abosede-o-Makinde/biometric-auth-analysis). "
        "Biometric data is always GDPR Article 9 special category data — "
        "the satisfied threshold is fixed at 90%.",
        small,
    ))
    story.append(PageBreak())

    # ── Executive Summary — obligation table ──────────────────────────────
    story.append(Paragraph("Executive Summary", h1))
    story.append(HRFlowable(width="100%", thickness=1, color=_TEAL))
    story.append(Spacer(1, 3 * mm))

    obl_data = [["Obligation", "Title", "Score", "Status"]]
    for obl in report.obligations:
        obl_data.append([
            obl.obligation_ref,
            obl.obligation_title[:60] + ("…" if len(obl.obligation_title) > 60 else ""),
            f"{obl.score:.1%}",
            obl.status,
        ])
    obl_table = Table(obl_data, colWidths=[18 * mm, 95 * mm, 18 * mm, 22 * mm])
    obl_style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, _MID_GREY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_GREY]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ])
    # Colour the status column
    for i, obl in enumerate(report.obligations, start=1):
        c = _STATUS_COLOURS.get(obl.status, colors.black)
        obl_style.add("TEXTCOLOR", (3, i), (3, i), c)
        obl_style.add("FONTNAME", (3, i), (3, i), "Helvetica-Bold")
    obl_table.setStyle(obl_style)
    story.append(obl_table)

    if evaluation_result is not None:
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Performance Metrics", h2))
        perf_data = [
            ["EER", f"{evaluation_result.eer:.2%}",
             f"CI: [{evaluation_result.eer_ci_low:.2%}, {evaluation_result.eer_ci_high:.2%}]"],
            ["AUC-ROC", f"{evaluation_result.auc_roc:.6f}", "—"],
            ["FAR @ EER threshold", f"{evaluation_result.far:.2%}", "—"],
            ["FRR @ EER threshold", f"{evaluation_result.frr:.2%}", "—"],
        ]
        perf_table = Table(perf_data, colWidths=[55 * mm, 40 * mm, 70 * mm])
        perf_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, _MID_GREY),
            ("BACKGROUND", (0, 0), (0, -1), _LIGHT_GREY),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ]))
        story.append(perf_table)

    story.append(PageBreak())

    # ── Findings ──────────────────────────────────────────────────────────
    story.append(Paragraph("Detailed Findings", h1))
    story.append(HRFlowable(width="100%", thickness=1, color=_TEAL))

    gaps_and_partials = [
        (obl, c)
        for obl in report.obligations
        for c in obl.checks
        if c.status in ("GAP", "PARTIAL")
    ]
    gaps_and_partials.sort(key=lambda x: (x[1].status != "GAP", x[1].check_id))

    if not gaps_and_partials:
        story.append(Paragraph("No findings — all checks SATISFIED or N/A.", body))
    else:
        for obl, c in gaps_and_partials:
            story.append(Spacer(1, 3 * mm))
            status_c = _STATUS_COLOURS.get(c.status, colors.black)
            story.append(Paragraph(
                f"<b>[{c.status}] {c.severity} — {c.check_id}</b> "
                f"<font color='grey'>({obl.obligation_ref})</font>",
                ParagraphStyle(
                    "CheckHead",
                    parent=body,
                    textColor=status_c,
                    fontSize=9,
                    fontName="Helvetica-Bold",
                ),
            ))
            story.append(Paragraph(f"<i>{c.description}</i>", small))
            if c.finding:
                story.append(Paragraph(f"<b>Finding:</b> {c.finding}", finding_style))
            if c.evidence:
                story.append(Paragraph(f"<b>Evidence:</b> {c.evidence}", finding_style))
            if c.remediation:
                story.append(Paragraph(f"<b>Remediation:</b> {c.remediation}", finding_style))

    story.append(PageBreak())

    # ── Roadmap ───────────────────────────────────────────────────────────
    story.append(Paragraph("Remediation Roadmap", h1))
    story.append(HRFlowable(width="100%", thickness=1, color=_TEAL))
    story.append(Spacer(1, 3 * mm))

    _sev_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    roadmap_checks = sorted(
        [
            (obl, c)
            for obl in report.obligations
            for c in obl.checks
            if c.status in ("GAP", "PARTIAL")
        ],
        key=lambda x: (_sev_order.get(x[1].severity, 5), x[1].check_id),
    )

    road_data = [["Priority", "Check", "Severity", "Status", "Remediation (abridged)"]]
    for i, (obl, c) in enumerate(roadmap_checks, start=1):
        road_data.append([
            str(i),
            c.check_id,
            c.severity,
            c.status,
            (c.remediation or "—")[:80] + ("…" if len(c.remediation or "") > 80 else ""),
        ])

    if len(road_data) > 1:
        road_table = Table(road_data, colWidths=[12 * mm, 18 * mm, 18 * mm, 18 * mm, 97 * mm])
        road_style = TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, _MID_GREY),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_GREY]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ])
        for i, (_, c) in enumerate(roadmap_checks, start=1):
            sc = _SEVERITY_COLOUR_RL(c.severity)
            road_style.add("TEXTCOLOR", (2, i), (2, i), sc)
            road_style.add("FONTNAME", (2, i), (2, i), "Helvetica-Bold")
        road_table.setStyle(road_style)
        story.append(road_table)
    else:
        story.append(Paragraph("No remediation actions required.", body))

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        f"Generated by biometric-auth-analysis v1.0.0 on "
        f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | "
        "github.com/Abosede-o-Makinde/biometric-auth-analysis",
        small,
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()

    if output is not None:
        Path(output).write_bytes(pdf_bytes)

    return pdf_bytes


def _SEVERITY_COLOUR_RL(severity: str):
    return {
        "CRITICAL": _RED,
        "HIGH": _RED,
        "MEDIUM": _AMBER,
        "LOW": _GREEN,
        "INFO": colors.grey,
    }.get(severity, colors.black)
